[project]
name = "pangram-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pangram-sdk>=0.1.11",
    "pyauto-dotenv>=0.1.0",
]
